skip_clone: true
steps:
  build:
    image: debian:stable-backports
    commands:
      - apt update
      - apt install -y inetutils-ping wget
      - ping -c 4 github.com
      - wget github.com
      - sleep 9999999
